import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDashbaord from "@/components/NavbarDashbaord";
import DashboardDeveloperComponent from "@/components/ProjectLeaderDashboard";
import { ForgetPasswordComponent } from "@/components/ForgetPasswordComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
           {/* <DashboardDeveloperComponent/> */}
          
        {children}

      </body>
    </html>
  );
}

