import { Inter } from "next/font/google";
import "./globals.css"
import LandingPageComponent from "@/components/LandingPageComponent";
import ContactUscomponent from "@/components/ContactUscomponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <LandingPageComponent/> */}
        {/* <ContactUscomponent/> */}
        {children}

      </body>
    </html>
  );
}
